#=> restore files from linux machine, job run at a particular timestamp is used for restore operation
---
  - hosts: local
    roles:
      - cohesity.cohesity_ansible_role
    tasks:
      - name: Restore Files
        include_role:
            name: cohesity.cohesity_ansible_role
            tasks_from: restore_file
        vars:
            cohesity_server: "{{ cohesity_cluster_server }}"
            cohesity_admin: "{{ var_cohesity_username }}"
            cohesity_password: "{{ cohesity_cluster_password }}"
            cohesity_validate_certs: "{{ var_validate_certs }}"
            cohesity_restore_file:
                name: "Ansible File Restore1"
                environment: "PhysicalFiles"
                job_name: "protect_vm"
                endpoint: "10.2.146.241"
                files:
                  - "/home/cohesity/Documents"
                wait_for_job: True
                state: "present"
                backup_timestamp: "2019-04-20:2:44"
