#=> Install cohesity agent on windows machines
---
- hosts: windows
  gather_facts: yes
  become: false
  roles:
      - cohesity.cohesity_ansible_role
  tasks:
    - name: Install new Cohesity Agent on each windows Server
      include_role:
          name: cohesity.cohesity_ansible_role
          tasks_from: win_agent
      vars:
          cohesity_server: "{{ cohesity_cluster_server }}"
          cohesity_admin: "{{ var_cohesity_username }}"
          cohesity_password: "{{ cohesity_cluster_password }}"
          cohesity_validate_certs: "{{ var_validate_certs }}"
          cohesity_agent:
              state: present
              reboot: True
