# => Find and start all active Cohesity Protection Jobs registered to a Cluster
---
  - hosts: localhost
    # => Please change these variables to connect
    # => to your Cohesity Cluster
    vars:
        var_cohesity_server: 10.10.10.10
        var_cohesity_admin: "admin"
        var_cohesity_password: "admin"
        var_validate_certs: False
        inventory_dir: "/Users/YOUR_PATH_HERE"
    gather_facts: no
    roles:
      - cohesity.cohesity_ansible_role
    tasks:
        # => Gather Cohesity Facts
        - name: Gather Cohesity Cluster Details
          cohesity_facts:
              cluster: "{{ var_cohesity_server }}"
              username: "{{ var_cohesity_admin }}"
              password: "{{ var_cohesity_password }}"
              validate_certs: "{{ var_validate_certs }}"
              state: complete
              include_sources: False
              include_jobs: True
              include_runs: False
              active_only: False
              include_deleted: False
          register: cohesity

        - name: Update Job if kVMware Job has less than 2 VMs
          cohesity_job:
            cluster: "{{ var_cohesity_server }}"
            username: "{{ var_cohesity_admin }}"
            password: "{{ var_cohesity_password }}"
            state: present
            name: Ansible-Facts-Demo
            environment: VMware
            protection_sources:
              - endpoint: vcenter.domain.com
            protection_policy: Bronze
            storage_domain: DefaultStorageDomain 
            include:
              #- LIST OF VMS here
              - Windows_PWSH
          loop: "{{ cohesity.cluster.protection.jobs | default([]) }}"
          when: item.environment == 'kVMware' and item.sourceIds | length < 3
          ignore_errors: True

          

        - name: "Write the Collected Facts to {{ inventory_dir }}/cohesity_facts.json"
          local_action: copy content="{{ cohesity.cluster.protection | to_nice_json }}" dest="{{ inventory_dir }}/cohesity_facts.json"