---
- name: "Cohesity Recovery Job: Restore a set of Virtual Machines"
  cohesity_restore_vm:
    cluster: "{{ cohesity_server }}"
    username: "{{ cohesity_admin }}"
    password: "{{ cohesity_password }}"
    validate_certs: "{{ cohesity_validate_certs }}"
    state:  "{{ cohesity_restore_vm.state | default('present') }}"
    name: "{{ cohesity_restore_vm.name | default('') }}"
    environment: "{{ cohesity_restore_vm.environment | default('Physical') }}"
    job_name: "{{ cohesity_restore_vm.job_name | default('') }}"
    endpoint: "{{ cohesity_restore_vm.endpoint | default('') }}"
    backup_id: "{{ cohesity_restore_vm.backup_id | default('') }}"
    vm_names: "{{ cohesity_restore_vm.vms | default('') }}"
    wait_for_job: "{{ cohesity_restore_vm.wait_for_job | default('yes') }}"
    wait_minutes: "{{ cohesity_restore_vm.wait_minutes | default(30) }}"
    datastore_id: "{{ cohesity_restore_vm.datastore_id | default('') }}"
    datastore_folder_id: "{{ cohesity_restore_vm.datastore_folder_id | default('') }}"
    network_connected: "{{ cohesity_restore_vm.network_connected | default('yes') }}"
    network_id: "{{ cohesity_restore_vm.network_id | default('') }}"
    power_state: "{{ cohesity_restore_vm.power_state | default('yes') }}"
    resource_pool_id: "{{ cohesity_restore_vm.resource_pool_id | default('') }}"
    prefix: "{{ cohesity_restore_vm.prefix | default('') }}"
    suffix: "{{ cohesity_restore_vm.suffix | default('') }}"
    vm_folder_id: "{{ cohesity_restore_vm.vm_folder_id | default('') }}"
  tags: always
