---
- name: "Cohesity Recovery Job: Restore a set of files"
  cohesity_restore_file:
    cluster: "{{ cohesity_server }}"
    username: "{{ cohesity_admin }}"
    password: "{{ cohesity_password }}"
    validate_certs: "{{ cohesity_validate_certs | default(False) }}"
    state:  "{{ cohesity_restore_file.state | default('present') }}"
    name: "{{ cohesity_restore_file.name | default('') }}"
    environment: "{{ cohesity_restore_file.environment | default('PhysicalFiles') }}"
    job_name: "{{ cohesity_restore_file.job_name | default('') }}"
    endpoint: "{{ cohesity_restore_file.endpoint | default('') }}"
    backup_id: "{{ cohesity_restore_file.backup_id | default('') }}"
    file_names: "{{ cohesity_restore_file.files | default('') }}"
    wait_for_job: "{{ cohesity_restore_file.wait_for_job | default('yes') }}"
    wait_minutes: "{{ cohesity_restore_file.wait_minutes | default(10) }}"
    overwrite: "{{ cohesity_restore_file.overwrite | default('yes') }}"
    preserve_attributes: "{{ cohesity_restore_file.preserve_attributes | default('yes') }}"
    restore_location: "{{ cohesity_restore_file.restore_location | default('') }}"
  tags: always
