#=> Create a new VMware protection Job to protect only a set of VMs given in the inventory
---
  - hosts: local
    gather_facts: no
    roles:
      - cohesity.cohesity_ansible_role
    tasks:
      - name: Protection job
        include_role:
          name: cohesity.cohesity_ansible_role
          tasks_from: job
        vars:
          cohesity_server: "{{ cohesity_cluster_server }}"
          cohesity_admin: "{{ var_cohesity_username }}"
          cohesity_password: "{{ var_cohesity_password }}"
          cohesity_validate_certs: "{{ var_validate_certs }}"
          cohesity_protection:
              state: present
              job_name: protect_vcenter
              storage_domain: "DefaultStorageDomain"
              policy: "Bronze"
              sources:
                - endpoint: "vcenter_ip_or_hostname"
              environment: "VMware"
              include: "{{ groups['include_vms'] }}"
