# => Unregister linux machines as Cohesity protection sources
---
  - hosts: local
    gather_facts: no
    roles:
      - cohesity.cohesity_ansible_role
    tasks:
      # => Cycle through each member of the linux hosts and unregister as Cohesity Protection Source
      - name: Create new Protection Source for each Physical linux Server
        include_role:
            name: cohesity.cohesity_ansible_role
            tasks_from: source
        vars:
            cohesity_server: ""{{ cohesity_cluster_server }}""
            cohesity_admin: "{{ var_cohesity_username }}"
            cohesity_password: "{{ cohesity_cluster_password }}"
            cohesity_validate_certs: "{{ var_validate_certs }}"
            cohesity_source:
                state: absent
                endpoint: "{{item}}"
                environment: "Physical"
                host_type: "Linux"
        with_items: "{{groups['linux']}}"
