# => Collection: cohesity.cohesity_collection
# =>

#=> Stop a running protection job.
---
  - hosts: workstation
    gather_facts: no
    collections:
      - cohesity.cohesity_collection
    vars:
      cohesity_server: cluster_vip
      cohesity_admin: admin
      cohesity_password: admin
      cohesity_validate_certs: false
    tasks:
      - name: Stop Protection job
        cohesity_job:
          cluster: "{{ cohesity_server }}"
          username: "{{ cohesity_admin }}"
          password: "{{ cohesity_password }}"
          validate_certs: "False"
          state: "stopped"
          name: "DeleteJob"
          cancel_active: true
          environment: "VMware"
