#=> Stop protection job run
---
  - hosts: local
    gather_facts: no
    roles:
      - cohesity.cohesity_ansible_role
    tasks:
      - name: Start On-Demand Protection Job Execution
        include_role:
          name: cohesity.cohesity_ansible_role
          tasks_from: job
        vars:
          cohesity_server: "{{ cohesity_cluster_server }}"
          cohesity_admin: "{{ var_cohesity_username }}"
          cohesity_password: "{{ var_cohesity_password }}"
          cohesity_validate_certs: "{{ var_validate_certs }}"
          cohesity_protection:
              state: stopped
              job_name: "protect_vm"
