---
  - hosts: localhost
    # => Please change these variables to connect
    # => to your Cohesity Cluster
    vars:
        protection_job_name: protect_nas
        var_export_path: chandu-ve-01-vip.pm.cohesity.com:/Insight-View01
    gather_facts: no
    roles:
        - cohesity.cohesity_ansible_role
    tasks:
      - name: Create new Protection Job for Physical Linux Servers
        include_role:
          name: cohesity.cohesity_ansible_role
          tasks_from: job
        vars:
            cohesity_server: "{{ var_cohesity_server }}"
            cohesity_admin: "{{ var_cohesity_username }}"
            cohesity_password: "{{ var_cohesity_password }}"
            cohesity_validate_certs: "{{ var_validate_certs }}"
            cohesity_protection:
                state: present
                job_name: "{{ protection_job_name }}"
                environment: GenericNas
                sources:
                    - endpoint: "{{ var_export_path }}"
               
